const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Behaviors.wrap,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Pin,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.StopAll
	];
};
self.C3_JsPropNameTable = [
	{FundoEmBlocos: 0},
	{VIDA: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Jogador: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{Esmaecer: 0},
	{Mouse: 0},
	{VIDAMONSTRO2: 0},
	{DarAVolta: 0},
	{monstro: 0},
	{explosao: 0},
	{SCORE: 0},
	{Âncora: 0},
	{Fixar: 0},
	{gameover: 0},
	{Teclado: 0},
	{VIDAMONSTRO1: 0},
	{fantasma: 0},
	{Áudio: 0},
	{Sprite: 0},
	{INICIAR: 0},
	{cabou: 0},
	{Sprite2: 0}
];

self.InstanceType = {
	FundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Projétil: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	monstro: class extends self.ISpriteInstance {},
	explosao: class extends self.ISpriteInstance {},
	SCORE: class extends self.ITextInstance {},
	gameover: class extends self.ITextInstance {},
	Teclado: class extends self.IInstance {},
	fantasma: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	INICIAR: class extends self.IButtonInstance {},
	VIDA: class extends self.ITextInstance {},
	cabou: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {}
}